name: word_cloud_poc
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  kiwi: ^4.0.1
  get: ^4.6.1
  flutter_riverpod: ^1.0.3

  firebase_core: ^1.0.2
  firebase_auth: ^1.0.1
  firebase_database: ^9.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true


  # assets:
  #   - images/
